#!/bin/bash
set -euo pipefail
# This should turn into https://github.com/bootc-dev/bootc/issues/1498

dn=$(cd $(dirname $0) && pwd)

variant=$1
shift
# The un-sealed container image we want to use
input_image=$1
shift
# The output container image
output_image=$1
shift

runv() {
  set -x
  "$@"
}

case $variant in
  ostree)
    # Nothing to do
    echo "Not building a sealed image; forwarding tag"
    runv podman tag $input_image $output_image
    exit 0
    ;;
  composefs-sealeduki*)
    ;;
  *) 
    echo "Unknown variant=$variant" 1>&2; exit 1
    ;;
esac

cfs_digest=$(${dn}/compute-composefs-digest $input_image)
runv podman build -t $output_image \
  --build-arg=COMPOSEFS_FSVERITY=${cfs_digest} --build-arg=base=${input_image} "$@" -f Dockerfile.cfsuki .
